### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bycajisha** [chingu-voyages/v39-toucans-team-01#17]
As a website visitor, I want a homepage that is easy to use so that I can search for movies and have recommended movies available to me. 

Given a website visitor is on the site for the first time, when they search for a movie or select a recommended movie (randomized) then they should be able to locate the search bar to find other films, filter genres, or link to a recommended movie.

**Acceptance Criteria**

- [ ] Website title 
- [ ] Search bar that pulls from movie database and populates to display matching titles based on the keyword search
- [ ] Banner with a movie that is randomized from the database
- [ ] "Browse" tab with sub-menu: "genre", "streaming sites", "actors", "directors" (these will all be their own page that pulls this information from the database and displays it)

Additional Resources: https://www.figma.com/file/9aTia8WrNhAzM0Wtv6tWRe/Team-Toucan-01?node-id=0%3A1 

Banner Image from Figma Attached. 

![Image](https://user-images.githubusercontent.com/17421359/166588628-5128be8f-15cd-4d39-a17b-26c97cb8f360.png)
