### ISSUE TITLE
404 Error Status Page

### ISSUE THREAD

**Issue by bycajisha** [chingu-voyages/v39-toucans-team-01#18]
As a website visitor, I want to know when I have reached an error page so that I can return back to the previous link or refresh my page. 

Given that the website is still being built, when users stumble upon a link that may not lead to any particular page on our server then they should see that error page. 

**Acceptance Criteria:**

- [ ] Display error code: 404 
- [ ] Button that links back to homepage 
- [ ] Randomized movie with "learn more" button
