### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bycajisha** [chingu-voyages/v39-toucans-team-01#19]
The homepage is the landing page a user will encounter when they type in the URL and it needs to be easy for them to navigate the homepage. They will need to see a randomized movie option banner, search bar, and tab to browse for movies by genres, actors, and directors. 

**Major User Stories/Tasks:** 

- [ ]  Website title
- [ ]  Search bar that pulls from movie database and populates to display matching titles based on the keyword search
- [ ]  Hero Slider Banner with movies that are randomized from the database
- [ ] "Browse" tab with sub-menu items: "genre", "streaming sites", "actors", "directors" (these will all be their own page that pulls this information from the database and displays it)

Additional Resources: https://www.figma.com/file/9aTia8WrNhAzM0Wtv6tWRe/Team-Toucan-01?node-id=0%3A1

Banner Image from Figma Attached.

![Screen Shot 2022-05-03 at 7 22 24 PM](https://user-images.githubusercontent.com/17421359/166600901-0f6d5fc3-b346-43f7-8ffd-1ec4bb545aac.png)
